name: Build R images

env:
  VERSION: 4.5.1
  CRAN_CHECKPOINT_BINARY: https://packagemanager.posit.co/cran/__linux__/jammy/2025-11-17
  CRAN_CHECKPOINT_SOURCE: https://packagemanager.posit.co/cran/2025-11-17

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"  # Runs every day at 18:00 UTC (6:00 PM UTC)

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Switch to r-${{ env.VERSION }} branch
      run: git fetch && git checkout r-${{ env.VERSION }}

    - name: Set lowercase repository name as environment variable
      run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the image
      run: cd 1-rbase && docker build . --build-arg R_VERSION=${{ env.VERSION }} --build-arg CRAN_CHECKPOINT_BINARY=${{ env.CRAN_CHECKPOINT_BINARY }} --build-arg CRAN_CHECKPOINT_SOURCE=${{ env.CRAN_CHECKPOINT_SOURCE }} --tag ghcr.io/${{ env.REPO_NAME }}/rbase:${{ env.VERSION }}
        
    - name: Push the image to GHCR (versioned)
      run: docker push ghcr.io/${{ env.REPO_NAME }}/rbase:${{ env.VERSION }}
      
    - name: Clean up untagged images
      uses: actions/delete-package-versions@v5
      with: 
        package-name: 'cs/rbase'
        package-type: 'container'
        min-versions-to-keep: 0
        delete-only-untagged-versions: 'true'